import type { Metadata } from "next";

import { getSession } from "@auth0/nextjs-auth0";

import Providers from "./Providers";

import Lead from "./components/navigation/Lead";

import "../styles/styles.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = (await getSession()) || {};
  return (
    <html lang="en" data-theme="dark" style={{ colorScheme: "dark" }}>
      <meta name="viewport" content="initial-scale=1, width=device-width" />

      <body className="chakra-ui-dark">
        <Providers>
          <Lead />

          {children}
        </Providers>
      </body>
    </html>
  );
}
